docker-compose-yaml: docker-compose.yml

project: drupal9-example-simple

tasks:
#   pre-rollout:
#     - run:
#         name: drush sql-dump
#         command: mkdir -p /app/web/sites/default/files/private/ && drush sql-dump --ordered-dump --gzip --result-file=/app/web/sites/default/files/private/pre-deploy-dump.sql.gz || true
#         service: cli

#  post-rollout:
#    - run:
#        name: drush deploy
#        command: drush -y deploy
#        service: cli

environments:
  9.x:
    cronjobs:
      - name: drush cron
        schedule: "9 * * * *"
        command: drush cron
        service: cli
